# Generated by Django 3.2.18 on 2023-05-03 08:31

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_alter_placeorder_expected_deliverydate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddtoCart',
            new_name='Cart',
        ),
        migrations.AlterField(
            model_name='placeorder',
            name='expected_deliverydate',
            field=models.DateTimeField(default=datetime.date(2023, 5, 4)),
        ),
    ]
